if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_cards',
		'title' => 'Cards',
		'fields' => array (
			array (
				'key' => 'field_55338ce81eea3',
				'label' => 'Name',
				'name' => 'card_name',
				'type' => 'text',
				'instructions' => 'The name of the participant',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55338d151eea4',
				'label' => 'Profession',
				'name' => 'job',
				'type' => 'text',
				'instructions' => 'The job the participant did during the event',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55338e9a1eea5',
				'label' => 'Email',
				'name' => 'contact',
				'type' => 'text',
				'instructions' => 'The participant\'s email adress.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55338ede1eea6',
				'label' => 'Headshot Image',
				'name' => 'headshot_image',
				'type' => 'image',
				'instructions' => 'The headshot image of the participant.',
				'required' => 1,
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55338f6d1eea7',
				'label' => 'Project(s)',
				'name' => 'projects',
				'type' => 'text',
				'instructions' => 'The project or projects that the participant has participated in, expressed as the number Det Kolde Bord it was. 
	I.e. if the participant was a part of Det Kolde Bord #12 input the number "12" without the quotations.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'card',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_colors-and-images',
		'title' => 'Colors and Images',
		'fields' => array (
			array (
				'key' => 'field_553007175905e',
				'label' => 'Med Venlig Hilsen Color',
				'name' => 'mvh_color',
				'type' => 'color_picker',
				'instructions' => 'Pick color for the Med Venlig Hilsen page',
				'required' => 1,
				'default_value' => '#649DA9',
			),
			array (
				'key' => 'field_553007ff59061',
				'label' => 'Det Kolde Bord Color',
				'name' => 'dkb_color',
				'type' => 'color_picker',
				'instructions' => 'Pick color for the Med Venlig Hilsen page',
				'required' => 1,
				'default_value' => '#DE4E77',
			),
			array (
				'key' => 'field_553007655905f',
				'label' => 'Med Venlig Hilsen Header Image',
				'name' => 'mvh_header_img',
				'type' => 'image',
				'instructions' => 'Add / Edit the image shown at the top of the Med Venlig Hilsen pages.',
				'required' => 1,
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_5530084b59062',
				'label' => 'Det Kolde Bord Header Image',
				'name' => 'dkb_header_img',
				'type' => 'image',
				'instructions' => 'Add / Edit the image shown at the top of the Med Venlig Hilsen pages.',
				'required' => 1,
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_55367649ed64d',
				'label' => 'Det Kolde Bord Logo',
				'name' => 'dkb_logo',
				'type' => 'image',
				'instructions' => 'The logo for Det Kolde Bord',
				'required' => 1,
				'save_format' => 'url',
				'preview_size' => 'full',
				'library' => 'all',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'look',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_formalities-facts-technicalities',
		'title' => 'Formalities, facts, technicalities',
		'fields' => array (
			array (
				'key' => 'field_553380e24201f',
				'label' => 'Facts Headline',
				'name' => 'facts_headline',
				'type' => 'text',
				'instructions' => 'The headline for the facts box below.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55337c592fade',
				'label' => 'Facts',
				'name' => 'facts',
				'type' => 'textarea',
				'instructions' => 'Here you can put in information like:
	adress, booking-info, price, playtime, when, where, etc.
	
	Formatting will be preserved.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 10,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'mvh',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'dkb',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'permalink',
			),
		),
		'menu_order' => 0,
	));
}
